name: Stock Market Predictor Automation

on:
  schedule:
    # Morning: 9:00 AM ET = 2:00 PM UTC (Monday-Friday) - Before market open
    - cron: '0 14 * * 1-5'
    # Evening: 5:00 PM ET = 10:00 PM UTC (Monday-Friday) - After market close
    - cron: '0 22 * * 1-5'
  
  # Allow manual trigger for testing
  workflow_dispatch:

jobs:
  morning-analysis:
    # Only run morning job at 9:00 AM or manual trigger
    if: github.event.schedule == '0 14 * * 1-5' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Download previous data (if exists)
      uses: actions/download-artifact@v3
      with:
        name: market-data
        path: .
      continue-on-error: true
    
    - name: Check for historical performance and prepare retraining
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        echo "Checking for historical performance data..."
        python retrain_with_history.py
    
    - name: Run data update and model training
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        echo "Starting morning analysis..."
        python main.py
        echo "Morning analysis complete!"
    
    - name: Generate 10 stock predictions JSON
      run: |
        echo "Generating 10 stock predictions..."
        python generate_predictions_json.py
        echo "Predictions JSON generated!"
    
    - name: Write predictions to database
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        echo "Writing predictions to Render database..."
        python write_to_database.py predictions
        echo "Predictions saved to database!"
    
    - name: Generate recommendations email
      run: |
        echo "Generating portfolio-based recommendations..."
        python generate_recommendations.py
        echo "Portfolio recommendations generated!"
    
    - name: Take morning portfolio snapshot
      run: |
        echo "Taking morning portfolio snapshot..."
        python -c "
        import sys; sys.path.insert(0, 'src')
        from portfolio_manager import PortfolioManager
        from performance_tracker_daily import PerformanceTracker
        import pandas as pd
        
        pm = PortfolioManager('portfolio.yaml')
        prices = pd.read_parquet('data/raw/prices.parquet')
        portfolio_df = pm.update_with_prices(prices)
        summary = pm.get_portfolio_summary(portfolio_df)
        
        tracker = PerformanceTracker()
        tracker.take_snapshot(portfolio_df, summary, market_open=True)
        print('Morning snapshot saved!')
        "
        echo "Morning snapshot complete!"
    
    - name: Upload recommendations artifact
      uses: actions/upload-artifact@v3
      with:
        name: recommendations
        path: recommendations.txt
        retention-days: 7
    
    - name: Save data for next run
      uses: actions/upload-artifact@v3
      with:
        name: market-data
        path: |
          data/raw/prices.parquet
          data/processed/features.parquet
          models/
          data/performance/
          predictions.json
        retention-days: 30
    
    - name: Send morning email with recommendations
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: 📊 Morning Stock Picks - 10 AI Predictions for Today
        to: ${{ secrets.EMAIL_TO }}
        from: Stock Predictor Bot
        body: file://recommendations.txt
        priority: high

  evening-performance:
    # Only run evening job at 5:00 PM ET = 10:00 PM UTC (market close)
    if: github.event.schedule == '0 22 * * 1-5'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Download market data from morning
      uses: actions/download-artifact@v4
      with:
        name: market-data
        path: .
      continue-on-error: true
    
    - name: Update prices for market close
      run: |
        echo "Fetching latest closing prices..."
        python -c "
        import sys; sys.path.insert(0, 'src')
        from fetch_prices import fetch_and_save_prices
        import yaml
        
        with open('config.yaml') as f:
            config = yaml.safe_load(f)
        
        fetch_and_save_prices(config['data']['tickers'])
        print('Closing prices updated!')
        "
    
    - name: Calculate end-of-day performance
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        echo "Calculating performance vs predictions..."
        python track_eod_performance.py
        echo "Performance calculated!"
    
    - name: Analyze stock movements with AI
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        echo "Analyzing why stocks moved using AI..."
        python analyze_stock_movements.py
        echo "Movement analysis complete!"
    
    - name: Write performance to database
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        echo "Saving performance to database..."
        python write_to_database.py performance
        echo "Performance saved!"
    
    - name: Generate evening summary with explanations
      run: |
        echo "Generating evening summary email..."
        python generate_evening_summary.py
        echo "Evening summary generated!"
    
    - name: Generate daily performance report
      run: |
        echo "Generating performance report with charts..."
        python generate_daily_performance.py
        echo "Performance report generated!"
    
    - name: Send evening summary email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: 📈 Daily Performance Summary - All 10 Stocks Results
        to: ${{ secrets.EMAIL_TO }}
        from: Stock Predictor Bot
        body: file://evening_summary.txt
        priority: normal
    
    - name: Send detailed performance report
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: 📊 Daily Performance Report - Market Close
        to: ${{ secrets.EMAIL_TO }}
        from: Stock Predictor Bot
        html_body: file://performance_report.html
        body: file://performance_report.txt
        priority: normal
    
    - name: Save updated performance data
      uses: actions/upload-artifact@v4
      with:
        name: market-data
        path: |
          data/raw/prices.parquet
          data/performance/
          performance.json
          movement_analyses.json
        retention-days: 30